import type { NextPage } from 'next';
import Head from 'next/head';
import { GetStaticProps, InferGetStaticPropsType } from 'next';
import { StyledApp } from '../../styles/App.styled';
import Todo from '../../components/Todo';


export const getStaticProps: GetStaticProps = async () => {
  const res = await fetch(`${process.env.API_HOST}/todos`);
  const todos = await res.json();

  return {
    props: {
      todos,
    },
  }
};



const Home: NextPage = ({ todos }: InferGetStaticPropsType<typeof getStaticProps>) => {
  const todosArray = todos.todos;

  return (
    <StyledApp>
      <Head>
        <title>Todo List Next.js</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Todo />
    </StyledApp>
  )
}

export default Home;
